name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare 
    steps:
      -uses: actions/checkout@v4
      -name: Deploy to Cloudflare Workers with Wrangler
       uses: cloudflare/wrangler-action@v3.13.1
       with:
         # Your Cloudflare API Token
         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
         # Your Cloudflare Account ID
         accountId:
